export default async function TimelineSidebarSummary() {
    const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
    await delay(3000);

    return (
        <p className="text-xs text-purple-dark/80 my-2 px-5">
            The client wanted a radical departure from traditional 'wellness' tropes. No lotus flowers, no soft pastel gradients. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla mollitia eos ut optio, harum iure commodi officiis doloribus assumenda sed ab eaque nobis fuga magnam voluptas ea. Excepturi eligendi consequuntur id velit omnis corporis eos! Porro neque sint consequatur doloribus minus expedita veniam omnis dicta repellendus voluptas, ea deserunt. Optio officia unde beatae deleniti placeat in commodi temporibus minima est delectus voluptates eaque sunt odit debitis, eveniet provident soluta culpa saepe fuga, dolorem quae voluptatibus. Doloremque sequi, non numquam cum repellat exercitationem fugiat a eveniet recusandae reiciendis placeat veniam tempore debitis totam fugit, perferendis, nemo error tenetur animi vitae beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, quibusdam? Porro ratione voluptate eligendi sequi perferendis? Rem assumenda earum repellendus dolore nisi! Eius, rem, accusamus quidem eum voluptates ex veniam aspernatur enim doloremque quasi deserunt laborum. Debitis in, fugit ab vero maiores quae quisquam vitae mollitia iusto? Minima repudiandae aliquid eligendi exercitationem corporis molestiae perspiciatis, maiores, ex iusto esse distinctio illo. Dolores inventore sint ea laudantium ipsum nihil? Voluptate distinctio nulla facere nobis minus dolor ea pariatur quidem, eveniet a, sit dolore nostrum veritatis quod inventore accusantium soluta saepe omnis! Ea quas officiis voluptatibus similique eos. Omnis eos commodi mollitia aliquid! Pariatur recusandae reprehenderit hic dicta libero facere enim ullam, commodi soluta nemo, nostrum necessitatibus molestias ad vitae impedit! Fugit est tempore optio qui iure amet molestias hic mollitia, nihil consequuntur aliquam cumque accusantium atque fugiat eligendi commodi, aperiam deleniti maiores quibusdam doloremque modi beatae deserunt. Voluptates ullam blanditiis neque.
        </p>
    )
} 