version: '3.8'

services:
  # 1. Local Redis (Replaces Vercel KV for autosave testing)
  redis:
    image: redis:7-alpine
    container_name: iteratipe-redis
    ports:
      - "6379:6379" # Maps your Windows port 6379 to the container's 6379

  # 2. Local PostgreSQL (Pre-Neon local testing environment)
  db:
    image: postgres:16-alpine
    container_name: iteratip-postgres
    restart: always
    environment:
      POSTGRES_USER: afrian
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iteratipe_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: